import Image from "next/image";
import Link from "next/link";
import { requireRole } from "../../lib/auth";
import { ORDER_STATUSES } from "../../lib/orders";
import { prisma } from "../../lib/prisma";
import { ADMIN_ROLES } from "../../lib/roles";
import { approveOrder, rejectOrder } from "./actions";
const money = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
export default async function AdminOrdersPage() { await requireRole(ADMIN_ROLES); const orders = await prisma.order.findMany({ where: { status: ORDER_STATUSES.WAITING_CONFIRMATION }, orderBy: { updatedAt: "asc" }, select: { id: true, orderNumber: true, amount: true, user: { select: { name: true, email: true } }, plan: { select: { name: true } }, paymentProof: { select: { fileUrl: true, note: true } } } }); return <main className="min-h-screen bg-[#071727] p-6 text-[#F5F0E7] sm:p-10"><header className="mx-auto flex max-w-6xl items-center justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-[#D6B56F]">Admin</p><h1 className="mt-2 text-3xl font-bold">Pending Orders</h1></div><Link href="/dashboard" className="text-sm text-[#D6B56F]">Dashboard</Link></header><section className="mx-auto mt-8 grid max-w-6xl gap-5">{orders.map((order) => <article key={order.id} className="grid gap-5 rounded-2xl border border-[#F5F0E7]/10 bg-[#0A1D30] p-5 md:grid-cols-[1fr_240px]"><div><h2 className="font-bold">{order.orderNumber}</h2><p className="mt-2 text-sm text-[#AEB8BE]">{order.user.name} · {order.user.email}</p><p className="mt-3">{order.plan.name} · {money.format(order.amount)}</p><p className="mt-2 text-sm">{order.paymentProof?.note}</p><div className="mt-5 flex gap-3"><form action={approveOrder.bind(null, order.id)}><button className="rounded-xl bg-emerald-400 px-5 py-2 font-bold text-[#071727]">Approve</button></form><form action={rejectOrder.bind(null, order.id)}><button className="rounded-xl border border-red-400/30 px-5 py-2 font-bold text-red-300">Reject</button></form></div></div>{order.paymentProof && <Image src={order.paymentProof.fileUrl} alt="Payment proof" width={240} height={180} unoptimized className="h-44 w-full rounded-xl object-contain" />}</article>)}{!orders.length && <p className="rounded-2xl border border-[#F5F0E7]/10 p-10 text-center text-[#AEB8BE]">No pending confirmations.</p>}</section></main>; }
