import Image from "next/image";
import Link from "next/link";
import { requireRole } from "../../lib/auth";
import { ORDER_STATUSES } from "../../lib/orders";
import { prisma } from "../../lib/prisma";
import { ADMIN_ROLES } from "../../lib/roles";
import { approveOrder, rejectOrder } from "./actions";

const money = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
const date = new Intl.DateTimeFormat("id-ID", { day: "numeric", month: "short", year: "numeric" });

export default async function AdminOrdersPage() {
  await requireRole(ADMIN_ROLES);
  const [orders, subscriptions] = await Promise.all([
    prisma.order.findMany({ where: { status: ORDER_STATUSES.WAITING_CONFIRMATION }, orderBy: { updatedAt: "asc" }, select: { id: true, orderNumber: true, amount: true, user: { select: { name: true, email: true } }, plan: { select: { name: true } }, paymentProof: { select: { fileUrl: true, note: true } } } }),
    prisma.subscription.findMany({ orderBy: { createdAt: "desc" }, take: 50, select: { id: true, status: true, startedAt: true, expiredAt: true, user: { select: { name: true, email: true } }, plan: { select: { name: true } }, order: { select: { orderNumber: true } } } }),
  ]);

  return <main className="min-h-screen bg-[#071727] p-6 text-[#F5F0E7] sm:p-10"><header className="mx-auto flex max-w-6xl items-center justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-[#D6B56F]">Admin</p><h1 className="mt-2 text-3xl font-bold">Orders</h1></div><Link href="/dashboard" className="text-sm text-[#D6B56F]">Dashboard</Link></header><section className="mx-auto mt-8 grid max-w-6xl gap-5"><h2 className="text-xl font-bold">Pending Confirmations</h2>{orders.map((order) => <article key={order.id} className="grid gap-5 rounded-2xl border border-[#F5F0E7]/10 bg-[#0A1D30] p-5 md:grid-cols-[1fr_240px]"><div><h3 className="font-bold">{order.orderNumber}</h3><p className="mt-2 text-sm text-[#AEB8BE]">{order.user.name} · {order.user.email}</p><p className="mt-3">{order.plan.name} · {money.format(order.amount)}</p><p className="mt-2 text-sm">{order.paymentProof?.note}</p><div className="mt-5 flex gap-3"><form action={approveOrder.bind(null, order.id)}><button className="rounded-xl bg-emerald-400 px-5 py-2 font-bold text-[#071727]">Approve</button></form><form action={rejectOrder.bind(null, order.id)}><button className="rounded-xl border border-red-400/30 px-5 py-2 font-bold text-red-300">Reject</button></form></div></div>{order.paymentProof && <Image src={order.paymentProof.fileUrl} alt="Payment proof" width={240} height={180} unoptimized className="h-44 w-full rounded-xl object-contain" />}</article>)}{!orders.length && <p className="rounded-2xl border border-[#F5F0E7]/10 p-10 text-center text-[#AEB8BE]">No pending confirmations.</p>}</section><section className="mx-auto mt-12 max-w-6xl"><h2 className="text-xl font-bold">Recent Subscriptions</h2><div className="mt-5 overflow-x-auto rounded-2xl border border-[#F5F0E7]/10"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#0A1D30] text-[#AEB8BE]"><tr><th className="p-4">Order</th><th className="p-4">User</th><th className="p-4">Plan</th><th className="p-4">Status</th><th className="p-4">Started</th><th className="p-4">Expires</th></tr></thead><tbody className="divide-y divide-[#F5F0E7]/10">{subscriptions.map((subscription) => <tr key={subscription.id}><td className="p-4 font-semibold">{subscription.order.orderNumber}</td><td className="p-4"><span className="block">{subscription.user.name}</span><span className="text-xs text-[#AEB8BE]">{subscription.user.email}</span></td><td className="p-4">{subscription.plan.name}</td><td className="p-4 text-[#F1DDA7]">{subscription.status}</td><td className="p-4">{date.format(subscription.startedAt)}</td><td className="p-4">{date.format(subscription.expiredAt)}</td></tr>)}</tbody></table></div>{!subscriptions.length && <p className="mt-5 rounded-2xl border border-[#F5F0E7]/10 p-8 text-center text-[#AEB8BE]">No subscriptions yet.</p>}</section></main>;
}
