"use client";

import Image from "next/image";
import { useActionState } from "react";
import type { PaymentFormState } from "../../incroet/payments/actions";

type Values = { name: string; type: string; mode: string; description: string | null; bankName: string | null; accountName: string | null; accountNumber: string | null; qrImageUrl: string | null; instructions: string | null };
const inputClass = "mt-2 min-h-12 w-full rounded-xl border border-[#F5F0E7]/10 bg-[#071727] px-4 text-sm outline-none focus:border-[#D6B56F]/50";

export function PaymentMethodForm({ action, values, submitLabel }: { action: (state: PaymentFormState, formData: FormData) => Promise<PaymentFormState>; values?: Values; submitLabel: string }) {
  const [state, formAction, pending] = useActionState(action, { error: null });
  return <form action={formAction} className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><label className="text-xs font-bold uppercase tracking-[.14em] text-[#AEB8BE]">Name<input name="name" required maxLength={100} defaultValue={values?.name} className={inputClass} /></label><label className="text-xs font-bold uppercase tracking-[.14em] text-[#AEB8BE]">Type<select name="type" required defaultValue={values?.type ?? "BANK_TRANSFER"} className={inputClass}><option value="BANK_TRANSFER">Bank Transfer</option><option value="QRIS">QRIS</option><option value="EWALLET">E-Wallet</option></select></label><label className="text-xs font-bold uppercase tracking-[.14em] text-[#AEB8BE]">Mode<select name="mode" required defaultValue={values?.mode ?? "STATIC"} className={inputClass}><option value="STATIC">Static</option></select></label></div><label className="block text-xs font-bold uppercase tracking-[.14em] text-[#AEB8BE]">Description<textarea name="description" rows={3} maxLength={2000} defaultValue={values?.description ?? ""} className={`${inputClass} py-3`} /></label><div className="grid gap-4 sm:grid-cols-3"><label className="text-xs font-bold uppercase tracking-[.14em] text-[#AEB8BE]">Bank Name<input name="bankName" maxLength={150} defaultValue={values?.bankName ?? ""} className={inputClass} /></label><label className="text-xs font-bold uppercase tracking-[.14em] text-[#AEB8BE]">Account Name<input name="accountName" maxLength={150} defaultValue={values?.accountName ?? ""} className={inputClass} /></label><label className="text-xs font-bold uppercase tracking-[.14em] text-[#AEB8BE]">Account Number<input name="accountNumber" maxLength={150} defaultValue={values?.accountNumber ?? ""} className={inputClass} /></label></div><div className="grid gap-5 sm:grid-cols-[1fr_auto] sm:items-end"><label className="text-xs font-bold uppercase tracking-[.14em] text-[#AEB8BE]">QR Image<input name="qrImage" type="file" accept="image/jpeg,image/png,image/webp" className={`${inputClass} py-3`} /><span className="mt-2 block text-[11px] font-normal normal-case tracking-normal">JPEG, PNG, atau WebP. Maksimal 5 MB.</span></label>{values?.qrImageUrl && <Image src={values.qrImageUrl} alt={`QR ${values.name}`} width={96} height={96} unoptimized className="h-24 w-24 rounded-xl border border-[#F5F0E7]/10 object-contain" />}</div><label className="block text-xs font-bold uppercase tracking-[.14em] text-[#AEB8BE]">Instructions<textarea name="instructions" rows={4} maxLength={2000} defaultValue={values?.instructions ?? ""} className={`${inputClass} py-3`} /></label>{state.error && <p role="alert" className="rounded-xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-200">{state.error}</p>}<button disabled={pending} className="min-h-12 rounded-xl bg-[#D6B56F] px-6 text-sm font-bold text-[#071727] hover:bg-[#F1DDA7] disabled:opacity-60">{pending ? "Menyimpan..." : submitLabel}</button></form>;
}
