import type { Metadata } from "next";
import Link from "next/link";
import { requireRole } from "../../lib/auth";
import { prisma } from "../../lib/prisma";
import { ROLES } from "../../lib/roles";
import { deletePaymentMethod, togglePaymentMethod } from "./actions";

export const metadata: Metadata = { title: "Payments — Super Admin Ruang Momen" };

export default async function PaymentsPage() {
  await requireRole(ROLES.SUPER_ADMIN);
  const methods = await prisma.paymentMethod.findMany({ orderBy: [{ active: "desc" }, { name: "asc" }], select: { id: true, name: true, type: true, mode: true, bankName: true, accountName: true, accountNumber: true, qrImageUrl: true, active: true } });
  return <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#D6B56F]">Payment Manager</p><h2 className="mt-2 text-2xl font-extrabold">Manual Payment Methods</h2><p className="mt-2 text-sm text-[#AEB8BE]">Konfigurasi pembayaran statis untuk integrasi checkout mendatang.</p></div><Link href="/superadmin/payments/new" className="inline-flex min-h-12 items-center rounded-xl bg-[#D6B56F] px-5 text-sm font-bold text-[#071727] hover:bg-[#F1DDA7]">Create Method</Link></div><div className="mt-6 overflow-x-auto rounded-[1.5rem] border border-[#F5F0E7]/[.08] bg-[#0A1D30]"><table className="w-full min-w-[980px] text-left text-sm"><thead className="border-b border-[#F5F0E7]/[.08] text-xs uppercase tracking-[.12em] text-[#AEB8BE]"><tr><th className="px-5 py-4">Name</th><th className="px-5 py-4">Type</th><th className="px-5 py-4">Mode</th><th className="px-5 py-4">Bank</th><th className="px-5 py-4">Account</th><th className="px-5 py-4">QR Available</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-[#F5F0E7]/[.07]">{methods.map((method) => <tr key={method.id}><td className="px-5 py-4 font-bold">{method.name}</td><td className="px-5 py-4 font-mono text-xs text-[#F1DDA7]">{method.type}</td><td className="px-5 py-4">{method.mode}</td><td className="px-5 py-4">{method.bankName ?? "—"}</td><td className="px-5 py-4"><p>{method.accountName ?? "—"}</p><p className="mt-1 text-xs text-[#AEB8BE]">{method.accountNumber ?? ""}</p></td><td className="px-5 py-4">{method.qrImageUrl ? "Yes" : "No"}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${method.active ? "bg-emerald-400/10 text-emerald-300" : "bg-[#F5F0E7]/[.06] text-[#AEB8BE]"}`}>{method.active ? "Active" : "Inactive"}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Link href={`/superadmin/payments/${method.id}/edit`} className="inline-flex min-h-10 items-center rounded-lg border border-[#D6B56F]/20 px-3 font-semibold text-[#F1DDA7]">Edit</Link><form action={togglePaymentMethod.bind(null, method.id)}><button className="min-h-10 rounded-lg border border-[#F5F0E7]/10 px-3 font-semibold text-[#AEB8BE]">{method.active ? "Deactivate" : "Activate"}</button></form><form action={deletePaymentMethod.bind(null, method.id)}><button className="min-h-10 rounded-lg border border-red-400/20 px-3 font-semibold text-red-300">Delete</button></form></div></td></tr>)}</tbody></table>{!methods.length && <p className="px-6 py-12 text-center text-[#AEB8BE]">Belum ada metode pembayaran.</p>}</div></section>;
}
